### ISSUE TITLE
Use CIJELI for int

### ISSUE THREAD

**Issue by ElectroBoy404NotFound** [ringwormGO-organization/Translated#1]
Hello! According to google translate, the name for int translates to "Number". So i wanted to know what Integer is and it is "CIJELI". So, why not use that?

**Comment by Andrej123456789** [comment]
Fixed. Issue will be closed

**Comment by ElectroBoy404NotFound** [comment]
ok

**Comment by ElectroBoy404NotFound** [comment]
@Andrej123456789 it is not fixed in README
